"""``app.pipeline.gcode_meta.parse_gcode_meta`` tests (R10-B, plan item 10):
PrusaSlicer/OrcaSlicer/Bambu Studio comment-header fixtures, plus a
counting-reader proof that a large file is never fully read.
"""

from __future__ import annotations

import io
import zipfile

from app.pipeline.gcode_meta import _CHUNK_BYTES, parse_gcode_meta

PRUSA_HEADER = b"""; generated by PrusaSlicer 2.7.0 on 2026-01-01 at 12:00:00
; estimated printing time (normal mode) = 1h 23m 4s
; filament used [mm] = 3456.78
; filament used [g] = 12.34
; filament_type = PLA
; layer_height = 0.2
; sparse_infill_density = 15%
; nozzle_temperature = 220,220
G1 X0 Y0
"""

ORCA_HEADER = b"""; generated by OrcaSlicer 2.1.0 on 2026-02-02
; estimated printing time (normal mode) = 55m 30s
; total filament used [g] = 8.5
; filament_type = PETG
; layer_height = 0.16
; fill_density = 20%
G1 X0 Y0
"""

BAMBU_HEADER = b"""; HEADER_BLOCK_START
; BambuStudio 1.9.0
; model printing time: 1h 2m 3s; total estimated time: 1h 5m 0s
; total filament weight [g]: 20.5
; total layer number: 250
; HEADER_BLOCK_END
G1 X0 Y0
"""


def test_parse_prusa_header() -> None:
    meta = parse_gcode_meta(io.BytesIO(PRUSA_HEADER))
    assert meta.duration_s == 3600 + 23 * 60 + 4
    assert meta.filament_g == 12.34
    assert meta.filament_mm == 3456.78
    assert meta.layer_height_mm == 0.2
    assert meta.infill_pct == 15
    assert meta.filament_type == "PLA"
    assert meta.slicer == "PrusaSlicer"


def test_parse_orca_header() -> None:
    meta = parse_gcode_meta(io.BytesIO(ORCA_HEADER))
    assert meta.duration_s == 55 * 60 + 30
    assert meta.filament_g == 8.5
    assert meta.layer_height_mm == 0.16
    assert meta.infill_pct == 20
    assert meta.filament_type == "PETG"
    assert meta.slicer == "OrcaSlicer"


def test_parse_bambu_header() -> None:
    meta = parse_gcode_meta(io.BytesIO(BAMBU_HEADER))
    assert meta.duration_s == 3600 + 5 * 60
    assert meta.layer_count == 250
    assert meta.slicer == "BambuStudio"


def test_footer_totals_override_header_estimates() -> None:
    data = (
        b"; generated by PrusaSlicer 2.7.0\n"
        b"; filament used [g] = 12.34\n"
        b"G1 X0 Y0\n"
        b"; total filament used [g] = 13.00\n"
    )
    meta = parse_gcode_meta(io.BytesIO(data))
    assert meta.filament_g == 13.00


class _CountingReader:
    """Wraps a ``BytesIO`` to record every byte count requested via
    ``.read(n)``, proving ``parse_gcode_meta`` never reads the whole body.
    """

    def __init__(self, data: bytes) -> None:
        self._buf = io.BytesIO(data)
        self.total_size = len(data)
        self.bytes_read = 0

    def read(self, size: int = -1) -> bytes:
        chunk = self._buf.read(size)
        self.bytes_read += len(chunk)
        return chunk

    def seek(self, offset: int, whence: int = 0) -> int:
        return self._buf.seek(offset, whence)

    def tell(self) -> int:
        return self._buf.tell()

    def seekable(self) -> bool:
        # Mimics a real file object opened `rb` (the fast head+seek+tail
        # path's intended target) -- genuinely random-access, unlike a
        # `zipfile.ZipExtFile` (see `test_zip_member_read_exactly_once`
        # below), whose `seekable()` lies.
        return True


def test_large_file_reads_only_head_and_tail() -> None:
    body = b"G1 X0 Y0\n" * 2_000_000  # tens of MB
    data = PRUSA_HEADER + body + b"; total filament used [g] = 12.34\n"
    reader = _CountingReader(data)

    meta = parse_gcode_meta(reader)

    assert meta.filament_type == "PLA"
    # Bounded well under the multi-MB body -- at most head + tail chunks.
    assert reader.bytes_read <= _CHUNK_BYTES * 2 + 1024
    assert reader.bytes_read < reader.total_size


def test_zip_member_read_exactly_once(tmp_path, monkeypatch) -> None:
    """A real ``zipfile.ZipExtFile`` reports ``seekable() == True`` but
    backward-seeking it re-decompresses from byte 0 -- the bug behind
    review finding 2 (``seek(0, 2)`` to find the size, then a backward
    seek to the tail, each a full decompression pass). The fix must
    recognize a `ZipExtFile` specifically and read it forward exactly
    once, never calling `.seek()` on it at all.
    """
    body = b"G1 X0 Y0\n" * 200_000
    data = PRUSA_HEADER + body + b"; total filament used [g] = 12.34\n"

    zpath = tmp_path / "plate.gcode.3mf"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("plate_1.gcode", data)

    with zipfile.ZipFile(zpath) as zf, zf.open("plate_1.gcode") as stream:
        assert stream.seekable()  # the misleading premise this test guards against

        bytes_read = 0
        orig_read = stream.read

        def counting_read(size: int = -1) -> bytes:
            nonlocal bytes_read
            chunk = orig_read(size)
            bytes_read += len(chunk)
            return chunk

        def forbidden_seek(*args: object, **kwargs: object) -> int:
            raise AssertionError("zip member must never be seeked")

        monkeypatch.setattr(stream, "read", counting_read)
        monkeypatch.setattr(stream, "seek", forbidden_seek)

        meta = parse_gcode_meta(stream)

        assert meta.filament_type == "PLA"
        assert meta.filament_g == 12.34
        # Exactly one forward pass: total bytes read equals the member's
        # exact decompressed size, never double it.
        assert bytes_read == len(data)
