"""baseline schema

Revision ID: 2a2ad98de9a4
Revises:
Create Date: 2026-07-04 23:26:27.959675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a2ad98de9a4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required by the pg_trgm GIN indexes on models.name/description below.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blobs",
        sa.Column("hash", sa.CHAR(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "mesh",
                "cad",
                "sliced",
                "gcode",
                "image",
                "other",
                name="blob_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum(
                "stl",
                "3mf",
                "obj",
                "step",
                "iges",
                "gcode_3mf",
                "gcode",
                "png",
                "jpg",
                "other",
                name="blob_format",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("hash", name=op.f("pk_blobs")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("celery_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("subject_type", sa.String(), nullable=True),
        sa.Column("subject_id", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_table(
        "printers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("bambu_lan", name="printer_kind", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("serial", sa.String(), nullable=False),
        sa.Column("access_code_enc", sa.Text(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printers")),
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("files_seen", sa.Integer(), server_default="0", nullable=False),
        sa.Column("files_hashed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("relinked", sa.Integer(), server_default="0", nullable=False),
        sa.Column("adopted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("missing", sa.Integer(), server_default="0", nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_runs")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "blob_meta",
        sa.Column("blob_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("triangle_count", sa.BigInteger(), nullable=True),
        sa.Column("dims_mm", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("volume_cm3", sa.Float(), nullable=True),
        sa.Column("surface_area_cm2", sa.Float(), nullable=True),
        sa.Column("is_watertight", sa.Boolean(), nullable=True),
        sa.Column("print_time_s", sa.Integer(), nullable=True),
        sa.Column("filament_g", sa.Float(), nullable=True),
        sa.Column("filament_m", sa.Float(), nullable=True),
        sa.Column("filament_types", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("layer_height", sa.Float(), nullable=True),
        sa.Column("nozzle", sa.Float(), nullable=True),
        sa.Column("printer_model", sa.Text(), nullable=True),
        sa.Column("plate_count", sa.Integer(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["blob_hash"],
            ["blobs.hash"],
            name=op.f("fk_blob_meta_blob_hash_blobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("blob_hash", name=op.f("pk_blob_meta")),
    )
    op.create_table(
        "derivatives",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("blob_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "thumb_256",
                "thumb_1024",
                "glb",
                "glb_preview",
                name="derivative_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ok",
                "failed",
                "unsupported",
                name="derivative_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tool", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blob_hash"],
            ["blobs.hash"],
            name=op.f("fk_derivatives_blob_hash_blobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_derivatives")),
        sa.UniqueConstraint("blob_hash", "kind", name=op.f("uq_derivatives_blob_hash")),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_site", sa.String(), nullable=True),
        sa.Column("source_author", sa.String(), nullable=True),
        sa.Column("source_license", sa.String(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_revision_id", sa.BigInteger(), nullable=True),
        sa.Column("cover_blob_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_blob_hash"],
            ["blobs.hash"],
            name=op.f("fk_models_cover_blob_hash_blobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"],
            ["revisions.id"],
            name="fk_models_current_revision_id_revisions",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("slug", name=op.f("uq_models_slug")),
    )
    op.create_index(
        "ix_models_description_trgm",
        "models",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_models_name_trgm",
        "models",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "site",
            sa.Enum(
                "thingiverse",
                "printables",
                "makerworld",
                name="import_site",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "fetching",
                "downloading",
                "done",
                "failed",
                name="import_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_id", sa.BigInteger(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_imports_model_id_models"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
    )
    op.create_table(
        "model_tags",
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("tag_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_model_tags_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_model_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("model_id", "tag_id", name=op.f("pk_model_tags")),
    )
    op.create_table(
        "revisions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("dir_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_revisions_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
        sa.UniqueConstraint("model_id", "number", name=op.f("uq_revisions_model_id")),
    )
    # models.current_revision_id -> revisions.id is a use_alter=True FK (circular
    # with revisions.model_id -> models.id): autogenerate's create_table render
    # for 'models' above omits it, so it must be added explicitly now that
    # 'revisions' exists.
    op.create_foreign_key(
        op.f("fk_models_current_revision_id_revisions"),
        "models",
        "revisions",
        ["current_revision_id"],
        ["id"],
    )
    op.create_table(
        "assembly_thumbs",
        sa.Column("revision_id", sa.BigInteger(), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ok",
                "failed",
                "unsupported",
                name="assembly_thumb_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
            name=op.f("fk_assembly_thumbs_revision_id_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("revision_id", name=op.f("pk_assembly_thumbs")),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("revision_id", sa.BigInteger(), nullable=False),
        sa.Column("blob_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("rel_path", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["blob_hash"], ["blobs.hash"], name=op.f("fk_files_blob_hash_blobs")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
            name=op.f("fk_files_revision_id_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("revision_id", "rel_path", name=op.f("uq_files_revision_id")),
    )
    op.create_index(op.f("ix_files_blob_hash"), "files", ["blob_hash"], unique=False)
    op.create_index(op.f("ix_files_revision_id"), "files", ["revision_id"], unique=False)
    op.create_index(op.f("ix_files_storage_path"), "files", ["storage_path"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("model_id", sa.BigInteger(), nullable=False),
        sa.Column("revision_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_notes_model_id_models"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
            name=op.f("fk_notes_revision_id_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_table(
        "print_jobs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("printer_id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("subtask_name", sa.String(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "uploading",
                "starting",
                "printing",
                "paused",
                "finished",
                "failed",
                "canceled",
                name="print_job_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("progress_pct", sa.Float(), nullable=True),
        sa.Column("remaining_min", sa.Integer(), nullable=True),
        sa.Column("layer", sa.Integer(), nullable=True),
        sa.Column("total_layers", sa.Integer(), nullable=True),
        sa.Column("printer_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_print_jobs_file_id_files")
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"], ["printers.id"], name=op.f("fk_print_jobs_printer_id_printers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_print_jobs")),
    )
    op.create_index(op.f("ix_print_jobs_state"), "print_jobs", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_print_jobs_state"), table_name="print_jobs")
    op.drop_table("print_jobs")
    op.drop_table("notes")
    op.drop_index(op.f("ix_files_storage_path"), table_name="files")
    op.drop_index(op.f("ix_files_revision_id"), table_name="files")
    op.drop_index(op.f("ix_files_blob_hash"), table_name="files")
    op.drop_table("files")
    op.drop_table("assembly_thumbs")
    op.drop_constraint(
        op.f("fk_models_current_revision_id_revisions"), "models", type_="foreignkey"
    )
    op.drop_table("revisions")
    op.drop_table("model_tags")
    op.drop_table("imports")
    op.drop_table("sessions")
    op.drop_index(
        "ix_models_name_trgm",
        table_name="models",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_models_description_trgm",
        table_name="models",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_table("models")
    op.drop_table("derivatives")
    op.drop_table("blob_meta")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("settings")
    op.drop_table("scan_runs")
    op.drop_table("printers")
    op.drop_table("jobs")
    op.drop_table("blobs")
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
